# GET all thoughts
GET http://localhost:3001/api/thoughts 

###
# GET one thought by ID
GET http://localhost:3001/api/thoughts/:id

###
# CREATE a thought
POST http://localhost:3001/api/thoughts
Content-Type: application/json

{
  "thoughtText": "Here's a cool thought...",
  "username": "awidener3"
}

###
# UPDATE a thought
PUT http://localhost:3001/api/thoughts/6218022c3fd0744a0f69515c
Content-Type: application/json

{
  "thoughtText": "Here's another cool thought...",
  "username": "awidener3"
}

###
# DELETE a thought
DELETE http://localhost:3001/api/thoughts/6218022c3fd0744a0f69515c

###
# ADD a reaction
POST http://localhost:3001/api//api/thoughts/:thoughtId/reactions

###
# DELETE a reaction
DELETE http://localhost:3001//api/thoughts/:thoughtId/reactions