# GET all users
GET http://localhost:3001/api/users 

###
# GET one user by ID
GET http://localhost:3001/api/users/621826b5646ea1e5f781e798

###
# CREATE a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "swidener",
    "email": "swidener@ti.com"
}

###
# UPDATE a user
PUT http://localhost:3001/api/users/621826b5646ea1e5f781e798
Content-Type: application/json

{
    "email": "jimbofisher@gmail.com"
}

###
# DELETE a user
DELETE http://localhost:3001/api/users/621826b5646ea1e5f781e798

###
# ADD a friend
POST http://localhost:3001/api/users/621826c0646ea1e5f781e79a/friends/62182701646ea1e5f781e7a2

###
# DELETE a friend
DELETE http://localhost:3001/api/users/621826c0646ea1e5f781e79a/friends/62182701646ea1e5f781e7a2